### ISSUE TITLE
Just dont work at all

### ISSUE THREAD

**Issue by notacodemonkey** [archaelus/esmtp#2]
No errors, no warnings no runtime errors, in tells me that result is ok, but no new mail appears in my mailbox.

**Comment by archaelus** [comment]
Yep - it's been broken for a while (since ssl changed around R13,R14). HEAD works against gmail right now (provided you do your own body "\r\n." escaping).

If you're still interested (my apologies for the delay) in esmtp, it'd be great if you could verify it does something useful for you now.
