### ISSUE TITLE
esmtp is not working with R14B

### ISSUE THREAD

**Issue by sendtopms** [archaelus/esmtp#5]
I used gmail a/c but it has lost of issues, 
1) connect(Host, Port, Type) --> Type receives the value 'new_ssl' but it suppose to be 'ssl'
2) sendemail({Host,Port,SSL,Login},Ehlo,From,To,Msg) -> 
      {ok, S1, {220, _Banner}} = esmtp_sock:read_response(S0) ends up returning {ok, S1, {220, _, _Banner}}
after that, decode is not aware of {PLAIN, AUTH}, am I missing something? 
Please help me.

**Comment by archaelus** [comment]
Mea culpa. This has been broken since at least R14A. The version in HEAD right now seems to work in my basic gmail testing - want to try it out and see if it works for you?
